type SiteConfig = {
  name: string;
  url: string;
  description: string;
  creator: string;
  authors: { name: string; url: string }[];
  keywords: string[];
  ogImage?: string;
  links: {
    github: string;
  };
};

export const siteConfig: SiteConfig = {
  name: "Potato Project",
  url: "https://potato-project-jkuat.vercel.app",
  description: "Generated by create-t3-app.",
  creator: "Peter Kibuchi",
  authors: [{ name: "Peter Kibuchi", url: "https://github.com/peterkibuchi" }],
  keywords: ["Potato Project"],
  links: {
    github: "https://github.com/peterkibuchi/potato-project",
  },
};
